= _Star Trek_ Database

This is a database containing metadata for all the episodes and movies
in the _Star Trek_ franchise.  It can be used to query information
about episode listings, DVD and Blu-ray contents, release dates, star
dates, and a few other miscellany.

At the time of the initial SQLite conversion, the database covers all
fourteen movies released and “classic _Star Trek_” television episodes
(up through the end of _Star Trek: Enterprise_).

One additional and unofficial entry in this database is _Star Trek
Continues_, because I am a fan of that fan-made series.

== Using it

At present, the repository only contains two files, +schema.sql+ and
+data.sql+, to initialize the database.  I have opted out of providing
a pre-built database file, but as long as you have `sqlite3` in your
+$PATH+, you can run

  $ make

to build up a +startrek.db+ file, through which you can use `sqlite3`
or any other SQLite interface to issue SQL commands.

== The future?

I have biased the media set tables primarily with media that I
actually own.  _Star Trek_ has been on virtually every kind of media
that has ever existed (LaserDisc, Betamax, VHS, etc), and there
remains a lot of room to document all of it.

As mentioned earlier, only classic _Star Trek_ is represented.  In the
earlier PostgreSQL version of the database, I had kept updates for
_Discovery_, _Lower Decks_, and _Picard_, but apathy towards the Alex
Kurtzman era caused me to become disinterested and I never stuck with
them to the end of their runs, and likewise did not update the
PostgreSQL version as episodes came out.  I’ll use the Postgres
database to reference what’s in there, and siphon data from Memory
Alpha for the rest.

Using an SQL database directly is not for everybody.  It might be nice
to make a GUI program or WebUI or something to interact with the
database.
